title: Homey Inspire
author: "@jekyllrb"
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  Home Appliance
tagline: How to and Buying Guide
permalink: /:year/:month/:day/:title.html
url: ""
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

version: 2
